spring.application.name=TD5-Sping-boot 2.0

spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=postgres
spring.datasource.password=19022007
spring.datasource.driver-class-name=org.postgresql.Driver

spring.web.error.include-message=always